command: huspy
version: 0.1

variables:
  BASE_URL: https://httpbin.org

headers:
  Authorization:
  X-Key: abcd-abcd-abcd-abcd-abcd

commands:
  # Get
  get <test>:
    endpoint: GET $BASE_URL/get
    description: A description of the command
    response: You got "$data.headers.Host" as a response. The user-agent is "$data.headers.User-Agent"

  get something:
    endpoint: GET $BASE_URL/get
    response: Another