command: huspy
version: 0.1

variables:
  BASE_URL: https://httpbin.org

headers:
  Authorization:
  X-Key: abcd-abcd-abcd-abcd-abcd

commands:
  # Get
  get:
    endpoint: GET $BASE_URL/get
    response: You got "$data.headers.Host" as a response. The priority is "$data.headers.Dnt"
