command: huspy
version: 0.1

variables:
  BASE_URL: https://httpbin.org
  BEARER_TOKEN: 

headers:
  Authorization: $BEARER_TOKEN
  X-Key: abcd-abcd-abcd-abcd-abcd

commands:
  # Get
  get <test>:
    endpoint: GET $BASE_URL/get
    description: A description of the command
    response: You got "$data.headers.Host" as a response. The user-agent is "$data.headers.User-Agent"
    set:
      BEARER_TOKEN: Bearer $data.headers.Host
      PIZZA: $data.headers.User-Agent

  get something:
    endpoint: POST $BASE_URL/post
    response: Another
  
  see <option>:
    endpoint: POST $BASE_URL/post?test=$option
    response: Option is $option
    set:
      PIZZA: $option
